### ISSUE TITLE
Catflow image

### ISSUE THREAD

**Issue by mmaelicke** [hydrocode-de/tool-runner#21]
We should get rid of the `images/*` folder soon. @AlexDo1 is there any progress on the `tool_catflow` repository? It is not yet online right?

**Comment by AlexDo1** [comment]
I just moved the catflow image stuff to [tool_catflow](https://github.com/AlexDo1/tool_catflow) and removed `images/*` from `tool-runner` with this [commit](https://github.com/hydrocode-de/tool-runner/commit/9af04a85c76d307503306e9cfd8a4c51f4409214).
